import Hero from "components/Hero";
import ProductsList from "components/ProductsList";
import { server } from "config";
import Head from "next/head";

export const getStaticProps = async () => {
  const response = await fetch(`${server}/api/avocado`);
  const { allAvocados: productList } = await response.json();

  return { props: { productList } };
};

const Home = ({ productList }: { productList: TProduct[] }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>
      <main>
        <>
          <Hero />
          <ProductsList products={productList} />
        </>
      </main>
    </div>
  );
};

export default Home;
